config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'search', to: 'search#search', as: :search

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/search_controller.rb
require 'securerandom'

class SearchController < ApplicationController

  before_action :validate_params, only: :search

  def search
    set_data

    render json: @data
  end

private

  def init_search
    uuid = SecureRandom.uuid

    SearchWorker.perform_async(uuid, params[:phrase], params[:engine])

    uuid
  end

  def set_data
    @data = if params[:uuid]
              Rails.cache.read(params[:uuid]) || { uuid: params[:uuid] }
            else
              { uuid: init_search }
            end
  end

  def validate_params
    head(:unprocessable_entity) and return unless ((params[:phrase] && params[:engine]) || params[:uuid])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index; end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.slim
doctype html
html
  head
    title SmTest
    meta name='viewport' content='width=device-width, initial-scale=1'
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'

  body
    = yield

app/views/welcome/index.slim
.container
  .row.mt-4
    .col.col-sm-6.offset-sm-3
      = form_tag search_path, method: :get, id: 'search-form'
        .form-group
          .input-group
            = text_field_tag 'phrase', nil, class: 'form-control'
            .input-group-append
              = button_tag 'Search', class: 'btn btn-primary'
        .form-group.text-center
          - Search::Initiator::SITES.each_pair do |key, value|
            .form-check.form-check-inline
              = radio_button_tag 'engine', key, checked: true, id: "engine-#{key}", class: 'form-check-input'
              = label_tag "engine-#{key}", value, class: 'form-check-label ml-1'
  .row
    .col.col-sm-8.offset-sm-2
      #progress.progress.d-none
        .progress-bar.progress-bar-striped.progress-bar-animated role='progressbar' style='width: 100%' aria-valuenow='100' aria-valuemin='0' aria-valuemax='100'
      #result.text-center